linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  tests: true


output:
  print-issued-lines: true
  print-linter-name: true